### ISSUE TITLE
Table Borders slightly misaligned

### ISSUE THREAD

**Issue by JosephRedfern** [bichenkk/coinmon#1]
An admittedly very minor problem, but on my machine (Ubuntu 17.10, node v6.11.4) the data-row columns are not properly aligned with the header columns.... [see here](https://asciinema.org/a/Tee0cHyaZPhnbHLa1nIzz07tz) or the attached image for a demo. I don't know if this is perhaps an emoji related issue?

![screenshot from 2017-11-20 14-04-31](https://user-images.githubusercontent.com/861949/33022077-d0459038-cdfb-11e7-83b8-0d09acea47fa.png)

**Comment by bichenkk** [comment]
Thanks for telling me this! I guess it is the emoji problem and let me check how to fix it.

**Comment by TheHolyWaffle** [comment]
On windows, it's a bit worse than that:

![image](https://user-images.githubusercontent.com/787914/33084891-606c8f3a-cee3-11e7-832a-efda87e0b5bd.png)

**Comment by desnudopenguino** [comment]
You might be able to resize it based on the screen (and shorten the titles). I have a tabular-style script (i know it's not node-based but still...) that detects the size of the terminal and resizes the data accordingly.

**Comment by bichenkk** [comment]
@desnudopenguino Thanks for the suggestion!
I have done some research and I guess I will remove the emoji and also the repeated currency code on price, 24h change and 1h change so it can be viewed in smaller screen.
