### ISSUE TITLE
Enhancement: Find support for multiple coins 

### ISSUE THREAD

**Issue by braggjc** [bichenkk/coinmon#11]
**Enhancement Request:**

Consider adding the ability to "find" multiple coins.  Possibly using comma/space delimited

> coinmon -f btc,neo,xrp,bcn,xmg,xmr,dash

if accepted. allow various sorting approaches, by symbol, price, change, etc....

**edit:**  justed looked at api looks like you may have to use:  /ticker/{id}/ to pull back specific coins..

**Comment by bichenkk** [comment]
@braggjc good suggestion. I will put it on the roadmap for coinmon!

**Comment by maticrivo** [comment]
@bichenkk when can we expect a new release in npm to use this feature?

**Comment by bichenkk** [comment]
@maticrivo Thanks for the commit. I am now testing and will release in an hour. :)

**Comment by bichenkk** [comment]
@maticrivo Thanks a lot. I have released 0.0.8 just now 👍 
@braggjc Please update and try with `npm update -g coinmon`!

Thanks a lot!

**Comment by maticrivo** [comment]
@bichenkk i created a new PR #14 to update the README file to show an example of multiple cryptocurrencies filter

**Comment by braggjc** [comment]
Looks great!!

Thanks!
