### ISSUE TITLE
Data display is unnecessarily wide

### ISSUE THREAD

**Issue by stvhwrd** [bichenkk/coinmon#17]
It would be awesome to have the displayed data fit into 80-char lines, as that is roughly the size of most terminal windows.   Currently, the rows are 92 characters long, so the table rows wrap in a standard ~80 and it doesn't look great:

<img src="https://user-images.githubusercontent.com/4117011/33140447-db1c8024-cf64-11e7-947d-02ed243c4a99.png" width="600">

Personally, I'd be happy to see fewer digits of market cap and a few less whitespace characters to make this possible.

**Comment by bichenkk** [comment]
@stvhwrd Thanks! I will adjust it soon!
