### ISSUE TITLE
Can't show the dollar symbol

### ISSUE THREAD

**Issue by leido** [bichenkk/coinmon#18]
![image](https://user-images.githubusercontent.com/6065941/33161976-e3f7216a-d061-11e7-820b-df2712e69e48.png)

**Comment by bichenkk** [comment]
@leido which OS is this?

**Comment by leido** [comment]
@bichenkk I'm using linux mint 18.2, which is based on Ubuntu 16.04.

**Comment by bichenkk** [comment]
@leido Thanks I will hide the emoji for Linux in next release. The terminal in Linux doesn’t support emoji @@

**Comment by DavidLiedle** [comment]
It is not an operating system issue, but rather one of terminal UTF-8 support and/or configuration. I would recommend keeping the icon/character, and using this as an opportunity to educate ourselves on proper system configuration with UTF-8 support. For example, on my Mac I run most terminal activities in GNU Screen, and apparently I have not properly configured that environment to display UTF-8 icons. Outside of Screen, I do see the icons in Apple's Terminal app, which indicates that it ships configured properly out-of-the-box. UTF-8 adoption has been painful over the years, but all of our tools should have the ability to display this properly when settings are correct. @bichenkk if you are so inclined, will you keep the icon and open an issue to add documentation on terminal/env config across various environments? If so, I will plan to submit PRs to cover the ones that I use as I am able.

**Comment by bichenkk** [comment]
@DavidLiedle Yes. Please do so! I in fact have no idea this is a UTF-8 issue and I thought the emoji only works for Mac device. That's why I added this commit.
https://github.com/bichenkk/coinmon/commit/4cf6b8f0c607267aa9bf284650a87cfa1788d5f8
