### ISSUE TITLE
Use versioning

### ISSUE THREAD

**Issue by pascalandy** [bichenkk/coinmon#28]
I love this project guy!
I use it via docker and I like to tag my image properly. I believe it would make sense to define a standard versioning for the project.

Cheers!
Pascal

**Comment by bichenkk** [comment]
Any better versioning method?

**Comment by pascalandy** [comment]
It's just that in the release section we can not see the version :-p

![screen shot 2018-01-03 at 1 14 31 pm](https://user-images.githubusercontent.com/6694151/34533414-1afc5400-f088-11e7-87cd-f4d9d2971e2d.jpg)

**Comment by pascalandy** [comment]
Well, I believe it should start at 0.1.0.
So far the project is stable so for me it deserves to be 1.0.0 :)

![screen shot 2018-01-03 at 1 14 31 pm](https://user-images.githubusercontent.com/6694151/34533452-48b4672a-f088-11e7-8ceb-495cf5ad19ee.jpg)

**Comment by bichenkk** [comment]
I see. Thanks a lot for the suggestion. I am going to rewrite most and release a more complete version in the upcoming future. Now I am more like testing different features.
