### ISSUE TITLE
Can we avoid the big splash at beginning ?

### ISSUE THREAD

**Issue by pascalandy** [bichenkk/coinmon#29]
As I like to run one command using US currency and the under one using CAD, it's a big annoying.

<img width="1260" alt="screen shot 2017-12-10 at 11 00 32 pm" src="https://user-images.githubusercontent.com/6694151/33815287-2ae549d6-ddfe-11e7-8b56-62ce83c961fc.png">

Cheers!

**Comment by bichenkk** [comment]
Thanks! I will think about removing this title if it causes problems. @@

**Comment by ditchfieldcaleb** [comment]
+1 for this - I run the command using watch, and the banner turns into terminal gibberish like so:
^[33m^[33m^[39m^[33m^[39m^[33m        ^[39m^[33m^[39m^[33m^[39m^[33m        ^[39m^[33m^[39m^[33m^[39m
^[33m      ^[39m^[33m^[39m^[33m^[39m^[33m         ^[39m^[33m^[39m^[33m^[39m^[33m             ^[39m^[3
3m^[39m^[33m^[39m^[33m        ^[39m^[33m^[39m^[33m^[39m^[33m         ^[39m^[33m^[39m^[33m^[39m
^[33m^[39m^[33m^[39m^[33m  ___   ^[39m^[33m^[39m^[33m^[39m^[33m  ___   ^[39m^[33m^[39m^[33m^[39m^[33m
 __   ^[39m^[33m^[39m^[33m^[39m^[33m  ___    ^[39m^[33m^[39m^[33m^[39m^[33m  ___ ___    ^[39m^[33m^[3
9m^[33m^[39m^[33m  ___   ^[39m^[33m^[39m^[33m^[39m^[33m  ___    ^[39m^[33m^[39m^[33m^[39m
^[33m^[39m^[33m^[39m^[33m /'___\ ^[39m^[33m^[39m^[33m^[39m^[33m / __`\ ^[39m^[33m^[39m^[33m^[39m^[33m
/\_\  ^[39m^[33m^[39m^[33m^[39m^[33m/' _ `\  ^[39m^[33m^[39m^[33m^[39m^[33m/' __` __`\  ^[39m^[33m^[3
9m^[33m^[39m^[33m / __`\ ^[39m^[33m^[39m^[33m^[39m^[33m/' _ `\  ^[39m^[33m^[39m^[33m^[39m
^[33m^[39m^[33m^[39m^[33m/\ \__/ ^[39m^[33m^[39m^[33m^[39m^[33m/\ \_\ \^[39m^[33m^[39m^[33m^[39m^[33m
\/\ \ ^[39m^[33m^[39m^[33m^[39m^[33m/\ \/\ \ ^[39m^[33m^[39m^[33m^[39m^[33m/\ \/\ \/\ \ ^[39m^[33m^[3
9m^[33m^[39m^[33m/\ \_\ \^[39m^[33m^[39m^[33m^[39m^[33m/\ \/\ \ ^[39m^[33m^[39m^[33m^[39m
^[33m^[39m^[33m^[39m^[33m\ \____\^[39m^[33m^[39m^[33m^[39m^[33m\ \____/^[39m^[33m^[39m^[33m^[39m^[33m
 \ \ \^[39m^[33m^[39m^[33m^[39m^[33m\ \_\ \_\^[39m^[33m^[39m^[33m^[39m^[33m\ \_\ \_\ \_\^[39m^[33m^[3
9m^[33m^[39m^[33m\ \____/^[39m^[33m^[39m^[33m^[39m^[33m\ \_\ \_\^[39m^[33m^[39m^[33m^[39m
^[33m^[39m^[33m^[39m^[33m \/____/^[39m^[33m^[39m^[33m^[39m^[33m \/___/ ^[3

**Comment by ditchfieldcaleb** [comment]
@pascalandy I just figured out if you pipe the output to tail, it completely removes the splash.

coinmon -f btc,eth,bay | tail

(adjust options for tail to get right if you're not grabbing 3 currencies like me)

**Comment by pascalandy** [comment]
Ya you're right. Tail will do the job :)

**Comment by hickscorp** [comment]
I think there should be a *--nologo* option. Having this huge logo and being forced to see it every time I run the tool:
- Requires more thinking to use the tool STDOUT,
- Brings *coinmon* further away from the *nix philosophy,
- Feels like I'm running Windows ;)

**Comment by hickscorp** [comment]
I decided to switch to https://github.com/hickscorp/coinmon (Which I coded this afternoon). It supports a portfolio file and outputs something like this:

![image](https://user-images.githubusercontent.com/822933/34321895-fb565a12-e810-11e7-8084-643cf493c790.png)

It also honours ANSI terminal colors.

**Comment by pascalandy** [comment]
I finally found the exact syntax for tail

`docker run --rm -ti devmtl/coinmon:0.9A coinmon -t 50 | tail -n +69;`
