### ISSUE TITLE
📝pyCOINMON port based on COINMON for Python 🐍

### ISSUE THREAD

**Issue by RDCH106** [bichenkk/coinmon#31]
This is a issue for public information about pyCOINMON port based on COINMON.

COINMON is a great project! Congrants! 🎉🎉🎉

But I think that the concept of the project may be more powerfull implemented with Python 🐍.
At this moment pyCOINMON has near to 90% of the functionality of COINMON.

It will be a pleasure to exchange ideas between the projects.

**Comment by bichenkk** [comment]
@RDCH106 Thanks!!! I treated this as a node.js practice and I did not expect there are so many people like this :) 

Sure! I am also learning python for data mining in school 📖
