### ISSUE TITLE
Coinmon doesn't respect terminal colors.

### ISSUE THREAD

**Issue by hickscorp** [bichenkk/coinmon#33]
If you have a customized colour scheme, `coinmon` ignores part of it. See screenshot, look at the logo.

![image](https://user-images.githubusercontent.com/822933/34320109-898505a4-e7e9-11e7-9c94-93792bd77163.png)

**Comment by bichenkk** [comment]
@hickscorp I have removed the logo and emoji to simplify the whole user experience.
For the color used for the changes, it is set as RED = negative and GREEN = positive.
