### ISSUE TITLE
Table header is missing a space

### ISSUE THREAD

**Issue by hickscorp** [bichenkk/coinmon#34]
The *Coin* table header is missing one space (Or maybe it's each coin *label* that have one extra space), making the row look weird. See attached screenie.

![image](https://user-images.githubusercontent.com/822933/34320115-c6c76f56-e7e9-11e7-911b-88e5509e41f3.png)

**Comment by sharang-d** [comment]
Looks like a duplicate of #1.

**Comment by bichenkk** [comment]
I have removed the emoji and it should work now. :) Please update.
