### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by anilkilic** [bichenkk/coinmon#41]
Hey,

It might not make sense for a CLI project but I made a simple logo, if you'd like to use.

![coinmon-v1](https://user-images.githubusercontent.com/2311397/35181766-13961224-fdd9-11e7-9fec-357ad387d088.png)

Editable vector files (.svg) are inside Archive.zip
[Archive.zip](https://github.com/bichenkk/coinmon/files/1648674/Archive.zip)

Font: Montserrat

**Comment by bichenkk** [comment]
This is nice! I love the second one :) I change it now.
