### ISSUE TITLE
Coinmon + Raspberry Pi 3

### ISSUE THREAD

**Issue by mahpoul22** [bichenkk/coinmon#42]
Hello,
I've been getting this issue, tried to install coinmon on a Raspberry Pi 3 with the latest Raspbian.
Node is installed.

Can you please point me in the right direction.

Thank you

`pi@raspberrypi:~ $ coinmon
/usr/local/lib/node_modules/coinmon/src/index.js:30
let portfolioEnabled;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3`

**Comment by bichenkk** [comment]
@mahpoul22 Can I know which node version are you using?

**Comment by olivia-ross** [comment]
I was having the same issue as the OP on a linux mint laptop. Based on the reply by you @bichenkk, I checked my version of node and updated and it is now working. I am new to github and I am impressed with how quickly this was taken care of for me (even though I wasn't the original poster). thanks!

**Comment by bichenkk** [comment]
@olivia-ross Thanks for the reply and support :)
@mahpoul22 Please update the node version to v6.0.0+ and it should work.

**Comment by mahpoul22** [comment]
@bichenkk 4.3.2

**Comment by bichenkk** [comment]
@mahpoul22 Node 4.3.2 should be too outdated for coinmon. Please try to update your node :) Update if you have any problems.
