### ISSUE TITLE
No support for proxies

### ISSUE THREAD

**Issue by swiggins83** [bichenkk/coinmon#5]
Hey there,

Perhaps I missed a part of some configuration but I cannot use coinmon behind a firewall.

> coinmon -t 10

                                                             
  ___     ___    __     ___      ___ ___      ___     ___    
 /'___\  / __`\ /\_\  /' _ `\  /' __` __`\   / __`\ /' _ `\  
/\ \__/ /\ \_\ \\/\ \ /\ \/\ \ /\ \/\ \/\ \ /\ \_\ \/\ \/\ \ 
\ \____\\ \____/ \ \ \\ \_\ \_\\ \_\ \_\ \_\\ \____/\ \_\ \_\
 \/____/ \/___/   \/_/ \/_/\/_/ \/_/\/_/\/_/ \/___/  \/_/\/_/
                                                             

Coinmon is not working now. Please try again later.

Is what I get every time running the command.
I suspect that this is a proxying issue.

**Comment by bichenkk** [comment]
Hi @swiggins83 I am using the the coinmarketcap api to do this tool.
Can you try if you can connect to https://api.coinmarketcap.com/v1/ticker/ ?
Thanks.
