### ISSUE TITLE
Make Market Cap values more readable 

### ISSUE THREAD

**Issue by TheJavaGuy** [bichenkk/coinmon#6]
Currently values in the Market Cap column are displayed without separators, like this 136782547484. I think it would be more readable if they are displayed like this 136 782 547 484 or this 136,782,547,484.

**Comment by joetech** [comment]
It would make sense to do the same for the Price column

**Comment by pgilad** [comment]
@joetech I disagree about prices - this is something you would probably want to see an exact figure on. Regarding market cap - it's very hard to read multi billion number (And to compare them as well), that's why it makes sense to have a humanized number for it (with an optional opt-out)

**Comment by bichenkk** [comment]
@pgilad Thanks for the commit. I will do the release tonight.
