### ISSUE TITLE
Feature Request: Data Not BS

### ISSUE THREAD

**Issue by callowaylc** [bichenkk/coinmon#62]
The point of a CLI, is to produce data, that can be run through an ETL pipeline, not visualizations - I could go to coinmarketcap for that. This is what I would currently have to do, just to determine price, so that it could be piped into a downstream process. 

```bash
$ docker run --rm -ti jaymoulin/coinmon:0.0.22 -s 2 | sed -n '7p' | awk '{ print $2 }'
5095.99288768
...
# instrument value
$ docker run --rm -ti jaymoulin/coinmon:0.0.22 -s 2 \
     | sed -n '7p' \
     | awk '{ print $2 }' \
     | xargs -I{} echo "price_btc {}" \
     | curl pushgatway/metrics/job/cryptosamplejob
```
 
If coinmon is **"The cryptocurrency price tool"**, then, like, give us the actual unmolested data, not a useless layout.

**Comment by bichenkk** [comment]
@callowaylc thanks for the comment. We are going to release a new update soon.
