### ISSUE TITLE
Died?

### ISSUE THREAD

**Issue by timshingyu** [bichenkk/coinmon#69]
It show

Coinmon is not working now. Please try again later

**Comment by kareemashraf** [comment]
i guess the coinmarketcap API used is deprecated, i will try to create a pull request to update it.

**Comment by kareemashraf** [comment]
the thing is , the data used to come from a deprecated coinmarketcap API now the new API is not for free anymore, im suggesting a pull request to depend on another free open source API such as https://docs.coincap.io/?version=latest
i will try to investigate and create a pull request for the update.

**Comment by tmlee** [comment]
Hey @kareemashraf how about looking into the CoinGecko API https://www.coingecko.com/en/api
No API keys needed and there are various endpoints that may suit the use case. It should be a quick drop in and integration.

**Comment by kareemashraf** [comment]
@tmlee i fixed it using the API you mentioned, now i cant push or create a pull request as it complains about permissions and returns error 403 Permission denied!

**Comment by tmlee** [comment]
I dont think the git push and pull is related to our API. It might have been github's server of sort?

**Comment by kareemashraf** [comment]
yeah that's exactly what i mean

**Comment by maborak** [comment]
#70 There is a pull request to work with coinmarketcap API KEY

**Comment by ThierryBegin** [comment]
seem that @bichenkk is not active much on Github anymore. we might need to find another solution here

**Comment by bichenkk** [comment]
@kareemashraf @ThierryBegin @tmlee  I'm sorry I was super busy last few months. Let me check how I can fix it easily and release a simpler version.

**Comment by ThierryBegin** [comment]
Absolutely no worries there, I just thought you became in active during these troubled times

**Comment by bichenkk** [comment]
@ThierryBegin @kareemashraf @tmlee Guys, I've done a quick fix for the project. It's now based on coincap API suggested by @kareemashraf .
However, I will need to remove some features temporarily first.

**Comment by ThierryBegin** [comment]
you don't know how you are making me happy right now

**Comment by timshingyu** [comment]
Thx @bichenkk
